"""Add datetime field to time_records

Revision ID: 0ee1a715abd7
Revises: ff3b89cbe296
Create Date: 2023-02-24 21:46:15.096683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee1a715abd7'
down_revision = 'ff3b89cbe296'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_records', sa.Column('datetime', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_records', 'datetime')
    # ### end Alembic commands ###
